### ISSUE TITLE
Page Build Failure Remote Theme

### ISSUE THREAD

**Issue by sonasapps** [thelehhman/plainwhite-jekyll#107]
I'm getting page build failures when using this as a remote theme:

```
The tag `seo` on line 7 in `/tmp/jekyll-remote-theme-20210913-6-o523pd/_includes/head.html` is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error
```

**Comment by sonasapps** [comment]
Any ideas how I can clear this @samarsault? Thanks!

**Comment by DotIN13** [comment]
I'm not sure but did you try installing jekyll-seo-tag gem with `bundle install`?

**Comment by sonasapps** [comment]
Hey @DotIN13! The thing is I'm not actually running it locally, I just deployed my Pages site and set the remote theme in _config.yml to plainwhite:

`remote_theme: samarsault/plainwhite-jekyll`

So I don't have any control over the file github is complaining about (at least if I'm understanding this correctly!)

**Comment by sonasapps** [comment]
I should add the site has been live for a while, I just went to make some changes and this error recently popped up.

**Comment by DotIN13** [comment]
Then I think you could check your Gemfile and config.yml, and try including jekyll-seo-tag in both of them to see how it works. As we see jekyll could not find the gem to call `seo`.

**Comment by sonasapps** [comment]
Thanks for the reply! I have no Gemfile for this repo
<img width="931" alt="image" src="https://user-images.githubusercontent.com/73260273/133359080-7a106074-8c2e-4513-b969-1d21f0405674.png">

I just tried adding the below to the config and get the same error.
  
  ```
  plugins:
  - jekyll-seo-tag
```

**Comment by DotIN13** [comment]
You could try creating a Gemfile with seo-tag, upload it to GitHub and see how it goes.

```ruby
source 'https://rubygems.org'
gemspec

gem 'jekyll'
gem 'jekyll-seo-tag'
```

**Comment by samarsault** [comment]
I tried reproducing this in https://github.com/samarsault/github-pages-remote-theme-test.

It seems to work after adding a plugin entry for jekyll-seo-tag as in the following:
https://github.com/samarsault/github-pages-remote-theme-test/commit/006a36228a2a1ebed5b8f096fedd092a2b31c0e5

This however, should work out of the box since this line is there in the theme's `_config.yml`

**Comment by sonasapps** [comment]
Thank you @samarsault -- apparently moving the plugin section to the top as in your example did the trick. Thank you so much! And thanks @DotIN13 for the support!

**Comment by 89hardy** [comment]
Hi @samarsault ! I'm facing a similar issue. Able to run it locally but build and deploy for pages is constantly failing:
https://github.com/89hardy/89hardy.github.io/actions
![image](https://user-images.githubusercontent.com/1505894/148909941-e0166567-0dbf-41de-b063-b1d0ac6cb897.png)
![image](https://user-images.githubusercontent.com/1505894/148910243-c05e4e65-cb9c-4141-833d-582661dd1548.png)


Note: It was throwing up the SEO error earlier and was failing locally too. So I removed it from head, default and gemfile and was able to run it locally then.

**Comment by mrwalakala** [comment]
> Hi @samarsault ! I'm facing a similar issue. Able to run it locally but build and deploy for pages is constantly failing: https://github.com/89hardy/89hardy.github.io/actions ![image](https://user-images.githubusercontent.com/1505894/148909941-e0166567-0dbf-41de-b063-b1d0ac6cb897.png) ![image](https://user-images.githubusercontent.com/1505894/148910243-c05e4e65-cb9c-4141-833d-582661dd1548.png)
> 
> Note: It was throwing up the SEO error earlier and was failing locally too. So I removed it from head, default and gemfile and was able to run it locally then.

Hi, i had the same issue and solved removing "theme" attribute from _config.yml files 
I also see a double "remote_theme" attribute in your _config.yml (this, right? 
https://github.com/89hardy/89hardy.github.io/blob/master/_config.yml ), maybe it's causing other trouble

**Comment by 89hardy** [comment]
That works. Thanks @mrwalakala

**Comment by funnykyeon** [comment]
Thanks, I solved it thanks to you too.@mrwalakala
