### ISSUE TITLE
Posts do not appear if they are dated 2022.

### ISSUE THREAD

**Issue by TemugeB** [thelehhman/plainwhite-jekyll#112]
```
---
layout: post
title:  "Title"
date:   2021-10-01 10:00:00 +0000
categories: cpp python
---
```
If ```date``` above is set to 2022, the post does not appear on the webpage. Changing the date to 2021 makes it appear on the site.

**Comment by cesarmiquel** [comment]
In my experience the date has to be in the past (or current date). 2022-10-01 would not display but 2022-06-23 (todays date) should display. Any post which has a future date will not show up. It's not a problem with 2022.

**Comment by TemugeB** [comment]
I see, thanks for your response. I uploaded a test post with today's date and the post does not show up. Changing the date to yesterday does make it appear. So it appears to be an issues with setting it to current date. It is definitely past 10:00 (Japan) but might be checking with Greenwich time? In which case the post would appear in the future. 

In any case, just setting to one day behind worked for me. Thanks.

**Comment by DotIN13** [comment]
It is likely that appearance of articles is subject to the local time of the building machine, so it might be UTC for github pages, or the system time if on some linux server.
