### ISSUE TITLE
How to add pages

### ISSUE THREAD

**Issue by sonasapps** [thelehhman/plainwhite-jekyll#114]
Hello! Thanks for this great theme. I've been able to add posts just fine to the _posts folder, which show on the main page. But where to I add new pages? Where I can have something like mysite.com/somenewpage. Thanks!

**Comment by DotIN13** [comment]
You can add pages directly in the root directory.

For example, if you need a new page at `mysite.com/somenewpage`, you can add a new file `somenewpage.md` in the exact same directory as `_config.yml`, which is also the root directory of the blog. And then add lines like below as the front matter, which tells jekyll which layout to use when rendering the page:

```markdown
---
layout: default
---
```

The layouts available resides in `_layouts`, where you can edit or add your own. The content of the page goes below the front matter.

You can also change the file extension into `.html` and write your page in HTML directly.

**Comment by sonasapps** [comment]
Terrific, this is working for me now. Thanks!
