### ISSUE TITLE
About theme in _config.yml

### ISSUE THREAD

**Issue by kevsersrca** [thelehhman/plainwhite-jekyll#17]
https://github.com/thelehhman/plainwhite-jekyll/blob/8d8900e621e1dceb701fd83674fc3d07329fbcaa/_config.yml#L52

If plainwhite , occur error 

```
You are attempting to use a Jekyll theme, "minimal", which is not supported by GitHub Pages.  
```

Please change it `minima`

**Comment by thelehhman** [comment]
How do I reproduce this?

**Comment by kevsersrca** [comment]
Write remote_theme instead of theme attr. Full content is [here](https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll).

Meanwhile, thanks for the theme. It's so clean :clap:

**Comment by thelehhman** [comment]
You'll have to use `thelehhman/plainwhite-jekyll` because the github pages gem uses the repository name for remote_theme.
