### ISSUE TITLE
jekyll v3.8.6

### ISSUE THREAD

**Issue by benniemosher** [thelehhman/plainwhite-jekyll#24]
When I try to bundle update off of this repo, I get an error:

```
Fetching https://github.com/thelehhman/plainwhite-jekyll
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 3.8.6)

    plainwhite was resolved to 0.9, which depends on
      jekyll (~> 3.7.3)
```

When I bundle update using my fork, it works. The only different is that my `.gemspec` file has `"jekyll", "~> 3.8.6"`.

https://github.com/benniemosher/plainwhite-jekyll/blob/master/plainwhite.gemspec#L15

However, when I try to create a PR to your repo here I do not get a change. Can I just submit a PR and branch right against this PR to update that or is there a better way? Please let me know. Thanks! 

pinging: @thelehhman for attention ;)

**Comment by thelehhman** [comment]
Fixed in https://github.com/thelehhman/plainwhite-jekyll/commit/eb36cd6d6571023ee342657ee4ced037108a41bd
