### ISSUE TITLE
Image not showing?

### ISSUE THREAD

**Issue by OscarJin** [thelehhman/plainwhite-jekyll#29]
i have written a blog using the theme, and an image is included.

`![Xi's Speech](../assets/200101/pic1.png)`

however, it can be displayed when i preview the file on [GitHub,](https://github.com/OscarJin/OscarJin.github.io/blob/master/_posts/2020-01-01-Chinese%20President%20Xi%20Jinping's%202020%20New%20Year%20speech.markdown) but the image cannot be displayed on my blog's [website.](https://oscarjin.github.io/essay/2020/01/01/Chinese-President-Xi-Jinping's-2020-New-Year-speech.html)
can anyone help me?

**Comment by thelehhman** [comment]
That is because during render, the browser resolves `..` as per the url & jekyll appends the category/tag, year, month to the url as well.
You should instead use relative paths, i.e.
```md
![Xi's Speech](/assets/200101/pic1.png)
```
Github previews the file accordingly because it resolves `..` as per the file system.

**Comment by OscarJin** [comment]
@thelehhman  it works. Thanks.
