### ISSUE TITLE
Creating markdown tables

### ISSUE THREAD

**Issue by AlexMussell** [thelehhman/plainwhite-jekyll#34]
Hey man,

Im trying to create markdown tables eg:
```
| a | b | c | d | e | f | g | h | i |
|---|---|---|---|---|---|---|---|---|
```
When rendering in VSCode, this table looks as it should. However, It just renders as a string.  Is this related to the theme in any way? How can i apply this myself otherwise?

**Comment by thelehhman** [comment]
You'll have to follow the github pages syntax:
https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

For example,
```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

```

**Comment by thelehhman** [comment]
Also, there are at present no explicit styles defined for a table, so you would have to style it yourself.
It would be great if you could submit a PR for that :)

**Comment by AlexMussell** [comment]
If I get some time, i'll look into it. Im not a frontend person by trade. If you want to see what I have done with your template, check out alexandermussell.com. Your template was a great start. Good stuff man.
