### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by skoruba** [thelehhman/plainwhite-jekyll#35]
Hey,
does it exist some why how to enable search in posts?
Thx

**Comment by DotIN13** [comment]
I've been using [this plugin](https://github.com/christian-fei/Simple-Jekyll-Search).

You could check it out. It's very easy to use. You just need to create a json, a search div in your HTML and add some JavaScript to your footer.

**Comment by thelehhman** [comment]
Added in https://github.com/thelehhman/plainwhite-jekyll/pull/37
