### ISSUE TITLE
hardcoded social sites

### ISSUE THREAD

**Issue by wbhamilton** [thelehhman/plainwhite-jekyll#38]
It seems the social sites are hardcoded in default.html to LinkedIn, GitHub, and Twitter. If I add Instagram in _config it doesn't appear on the homepage. What is the suggested fix for this? Thanks.

**Comment by thelehhman** [comment]
You'll have to add it yourself. See this for an example:
https://github.com/thelehhman/plainwhite-jekyll/blob/8b8a31f7b8b45365312229ea327e3dca123a346e/_layouts/default.html#L15-L21
Also, you would need to add the icon yourself.

**Comment by mikasjp** [comment]
The sample file `_config.yml` contains a rich list of social links. In my opinion, this suggests that you just uncomment them, and they will appear in the sidebar. It would be nice if they were implemented.

**Comment by nguyenvudao** [comment]
The Facebook icon hasn't been implemented. You cannot only change the name in `_config.yml` and `default.html`.

Its make difficult to add facebook's icon

**Comment by mikasjp** [comment]
Font Awesome or any alternative maybe?

**Comment by mikasjp** [comment]
It would also be nice if the user could set the icon order.

**Comment by thelehhman** [comment]
Plainwhite has, as of now, 3 social icons, i.e. github, linkedin and twitter. These icons are from FontAwesome but are bundled together into a single font file. The primary reason for doing this was to improve the website load time.
I believe that  adding the ones in the `_config.yml` wont be a major blow to performance, and is actually necessary for a `theme`.

A PR would be welcome for this :). If not, I'll try implementing this myself

**Comment by mikasjp** [comment]
To reduce loading time, you can embed Font Awesome from CDN and use the `brands` package, which only contains brand logos. :)

**Comment by cesarmiquel** [comment]
I just added a PR for this @thelehhman ! Hope you like it.
