### ISSUE TITLE
Soundcloud link to _config.yml

### ISSUE THREAD

**Issue by souviksaha97** [thelehhman/plainwhite-jekyll#47]
So I wanted to share my SoundCloud link on my profile, just like how you've provided, for Instagram, LinkedIn, and so on. Is that possible to implement? Thank you!

Also, I love this theme. It is so clean and professional at the same time!

Please check out my [page](https://souviksaha97.github.io/) once! Hope you like it.

**Comment by thelehhman** [comment]
Thanks @souviksaha97!
Check this out https://github.com/thelehhman/plainwhite-jekyll/pull/44

**Comment by souviksaha97** [comment]
Hey @thelehhman @jomei thanks for the update. Is there a way I can update this into my existing repo by updating the gemfile? I know I can update the site by forking the repo but I wanted to know if there's an alternative.

**Comment by thelehhman** [comment]
This change hasn't been pushed to rubygems, so I'm afraid you can't. The best way to stay up to date is to fork the repo.

**Comment by DotIN13** [comment]
Yeah I think you should fork first, and if you've done that before, maybe consider use git pull with this repo's remote. There could be some file conflicts tho, you may have to tinker'em by hand.
