### ISSUE TITLE
How to display real tables ?

### ISSUE THREAD

**Issue by jcabeza** [thelehhman/plainwhite-jekyll#52]
Hi,
How to display real tables with the contour display on posts ? 

Here's the display I'm getting, it's not too readable in the state
![image](https://user-images.githubusercontent.com/24415529/82322706-3ede5d00-99d7-11ea-8a3e-76c90df1e728.png)

Thanks for your work.

**Comment by thelehhman** [comment]
Oh, table styles had not been written yet. Thanks for point it out.
Added in https://github.com/thelehhman/plainwhite-jekyll/commit/f7939d095fa619b715e95009c39b609e3a51c813.
Here:
<img width="817" alt="Screenshot 2020-05-19 at 5 40 13 PM" src="https://user-images.githubusercontent.com/2987087/82324782-d6ec3e80-99f7-11ea-84b9-fcc78e893a66.png">

**Comment by jcabeza** [comment]
Review and test, it's ok ! 👍 
Thanks.
