### ISSUE TITLE
Icon for websites

### ISSUE THREAD

**Issue by souviksaha97** [thelehhman/plainwhite-jekyll#60]
Hello, can I add a personalised icon for the website? Thanks 👍

**Comment by thelehhman** [comment]
What do you mean by a personalised icon?
You can see https://github.com/thelehhman/plainwhite-jekyll/pull/55 for an example of how to add an icon.

**Comment by souviksaha97** [comment]
I'm referring to the icon that is shown on the tab in the browser, for example on github it's the black and white github cat.

**Comment by thelehhman** [comment]
You need to override the head, i.e. add the following to `_includes/head.html`
```html
<link rel="icon" href="path to favicon.ico">
```
If you are the gem based theme, you'll need to create a new file `_includes/head.html` with the content [here](https://github.com/thelehhman/plainwhite-jekyll/blob/master/_includes/head.html) and add the line above.

**Comment by souviksaha97** [comment]
Does it have to be favicon.ico ?

**Comment by thelehhman** [comment]
https://www.w3.org/2005/10/howto-favicon explains the details.

**Comment by souviksaha97** [comment]
I see. I was unaware of this earlier. Thanks!
